services:
  fastapi:
    image: jearora92331/fastapi:dev #replace with actual docker user id
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002:8000

  streamlit:
    image: jearora92331/streamlit:dev #replace with actual docker user id
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 9001:8501
    environment:
      API_URL: http://fastapi:8000